spring.application.name=unitat2


# ============================================================
#  Datasource (connexió a la base de dades)
# ============================================================

# Connexió a H2 en memòria (es crea cada cop que arrenca l'app)
spring.datasource.url=jdbc:h2:mem:testdb

# Driver JDBC d'H2
spring.datasource.driver-class-name=org.h2.Driver

# Usuari i password per defecte de h2
spring.datasource.username=sa
spring.datasource.password=

# ============================================================
#  Configuració JPA / Hibernate
# ============================================================

# Dialecte de la BBDD ? diu a Hibernate com ha de generar l'SQL per H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Estratègia de creació d'esquema:
#  - none       ? no fa res
#  - validate   ? valida que les taules existeixin
#  - update     ? crea/actualitza taules segons entitats
#  - create     ? elimina i crea les taules a cada arrencada
#  - create-drop? igual que create, però també elimina quan atures
spring.jpa.hibernate.ddl-auto=create

# Mostra l?SQL generat a la consola (molt útil per a docència)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#  Clau per a data.sql:
# Aquesta propietat fa que Spring Boot esperi a que Hibernate
# creï les taules abans d'executar data.sql (sinó dona error)
spring.jpa.defer-datasource-initialization=true

# ============================================================
#  Consola H2 web
# ============================================================

# Activa la consola H2 (per defecte desactivada)
spring.h2.console.enabled=true

# URL d?accés a la consola: http://localhost:8080/h2-console
spring.h2.console.path=/h2-console
